export { TabsList } from './Tabs/TabsList'
export { Product } from './Product/Product'
export { ProductDetails } from './Product-details/ProductDetails'
export { Header } from './Header/Header'
export { PreLoader } from './common/pre-loader/PreLoader'
export { ScrollArrow } from './common/scroll-arrow/ScrollArrow'